/*
 * SCIM 2.0 APIs Documentation
 * SCIM 2.0 APIs Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@wso2.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";

/**
* Scimv2Me service.
* @module api/Scimv2MeApi
* @version 1.0.0
*/
export class Scimv2MeApi {

    /**
    * Constructs a new Scimv2MeApi. 
    * @alias module:api/Scimv2MeApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createMe operation.
     * @callback moduleapi/Scimv2MeApi~createMeCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the user which was anonymously created
     * Returns HTTP 201 if the user is successfully created.
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Array.<String>} opts.attributes SCIM defined attributes parameter.
     * @param {Array.<String>} opts.excludedAttributes SCIM defined excludedAttribute parameter.
     * @param {module:api/Scimv2MeApi~createMeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createMe(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'attributes': this.apiClient.buildCollectionParam(opts['attributes'], 'csv'),'excludedAttributes': this.apiClient.buildCollectionParam(opts['excludedAttributes'], 'csv')
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/scim+json'];
      let accepts = ['application/json', 'application/scim+json'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/scim/v2/Me', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteMe operation.
     * @callback moduleapi/Scimv2MeApi~deleteMeCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete the authenticated user.
     * Returns HTTP 204 if the user is successfully deleted.
     * @param {module:api/Scimv2MeApi~deleteMeCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteMe(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/scim/v2/Me', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getMe operation.
     * @callback moduleapi/Scimv2MeApi~getMeCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the authenticated user.
     * Returns HTTP 200 if the user is found.
     * @param {Object} opts Optional parameters
     * @param {Array.<String>} opts.attributes SCIM defined attributes parameter.
     * @param {Array.<String>} opts.excludedAttributes SCIM defined excludedAttribute parameter.
     * @param {module:api/Scimv2MeApi~getMeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getMe(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'attributes': this.apiClient.buildCollectionParam(opts['attributes'], 'csv'),'excludedAttributes': this.apiClient.buildCollectionParam(opts['excludedAttributes'], 'csv')
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/scim+json'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/scim/v2/Me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the updateMe operation.
     * @callback moduleapi/Scimv2MeApi~updateMeCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the updated user
     * Returns HTTP 404 if the user is not found.
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Array.<String>} opts.attributes SCIM defined attributes parameter.
     * @param {Array.<String>} opts.excludedAttributes SCIM defined excludedAttribute parameter.
     * @param {module:api/Scimv2MeApi~updateMeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    updateMe(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'attributes': this.apiClient.buildCollectionParam(opts['attributes'], 'csv'),'excludedAttributes': this.apiClient.buildCollectionParam(opts['excludedAttributes'], 'csv')
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/scim+json'];
      let accepts = ['application/json', 'application/scim+json'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/scim/v2/Me', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}