/*
 * SCIM 2.0 APIs Documentation
 * SCIM 2.0 APIs Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@wso2.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";

/**
* Scimv2Bulk service.
* @module api/Scimv2BulkApi
* @version 1.0.0
*/
export class Scimv2BulkApi {

    /**
    * Constructs a new Scimv2BulkApi. 
    * @alias module:api/Scimv2BulkApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createBulk operation.
     * @callback moduleapi/Scimv2BulkApi~createBulkCallback
     * @param {String} error Error message, if any.
     * @param {'String'{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return the bulk which was created.
     * Returns HTTP 201 if the bulk is successfully created.
     * @param {Object} opts Optional parameters
     * @param {String} opts.body 
     * @param {Array.<String>} opts.attributes SCIM defined attributes parameter.
     * @param {Array.<String>} opts.excludedAttributes SCIM defined excludedAttribute parameter.
     * @param {module:api/Scimv2BulkApi~createBulkCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createBulk(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        'attributes': this.apiClient.buildCollectionParam(opts['attributes'], 'csv'),'excludedAttributes': this.apiClient.buildCollectionParam(opts['excludedAttributes'], 'csv')
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['basicAuth'];
      let contentTypes = ['application/scim+json'];
      let accepts = ['application/json', 'application/scim+json'];
      let returnType = 'String';

      return this.apiClient.callApi(
        '/scim/v2/Bulk', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}